theme: jekyll-theme-cayman
title: Creare programmando
description: Idee, tutorial e guide per ragazzi e ragazze dai 7 anni in su
google_analytics: UA-40873648-6
permalink: /blog/:year/:month/:day/:title
